# Generated by Django 3.2.4 on 2021-07-25 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('direccion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('direccion', models.TextField()),
                ('telefono', models.IntegerField()),
                ('correo', models.EmailField(max_length=254)),
                ('fechaIngreso', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('categoria', models.CharField(choices=[('1', 'Lácteos'), ('2', 'Carnes'), ('3', 'Bebidas'), ('4', 'Limpieza'), ('5', 'Abarrotes'), ('6', 'Enlatados'), ('7', 'Granos'), ('8', 'Dulces'), ('9', 'Otros')], default='1', max_length=1)),
                ('unidades_medidas', models.CharField(choices=[('1', 'Libras'), ('2', 'Kilos'), ('3', 'Cajas'), ('4', 'Docena'), ('5', 'Media docena'), ('6', 'Quintal'), ('7', 'Litros')], default='1', max_length=1)),
                ('cantidad', models.IntegerField()),
                ('precio_compra', models.FloatField()),
                ('precio_venta', models.FloatField()),
                ('apelllido', models.CharField(max_length=30)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_inventarioBodega.bodega')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordenVenta', models.CharField(max_length=5)),
                ('cantidadProducto', models.IntegerField()),
                ('PrecioProducto', models.IntegerField()),
                ('descuento', models.FloatField()),
                ('subTotal', models.FloatField()),
                ('totalVenta', models.FloatField()),
                ('fecha', models.DateField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='app_inventarioBodega.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordenTransferencia', models.CharField(max_length=5)),
                ('cantidadProducto', models.IntegerField()),
                ('PrecioProducto', models.IntegerField()),
                ('totalTransferencia', models.FloatField()),
                ('fecha', models.DateField()),
                ('bodegaDestino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bodegaDestino', to='app_inventarioBodega.bodega')),
                ('bodegaOrigen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bodegaOrigen', to='app_inventarioBodega.bodega')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto', to='app_inventarioBodega.producto')),
            ],
        ),
        migrations.AddField(
            model_name='bodega',
            name='encargado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_inventarioBodega.empleado'),
        ),
    ]
