# Generated by Django 3.2.3 on 2021-07-29 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inventarioBodega', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='unidades_medidas',
            field=models.CharField(choices=[('1', 'Libras'), ('2', 'Kilos'), ('3', 'Cajas'), ('4', 'Docena'), ('5', 'Media docena'), ('6', 'Quintal'), ('7', 'Litros'), ('8', 'Galon')], default='1', max_length=1),
        ),
    ]
