# Generated by Django 3.2.3 on 2021-07-28 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inventarioBodega', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='proveedor',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
