# Generated by Django 3.2.3 on 2021-07-26 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_inventarioBodega', '0002_producto_proveedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='apelllido',
        ),
    ]
