# Generated by Django 3.2.5 on 2021-07-24 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_inventarioBodega', '0002_remove_bodega_capacidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordenTransferencia', models.CharField(max_length=5)),
                ('cantidadProducto', models.IntegerField()),
                ('PrecioProducto', models.IntegerField()),
                ('totalTransferencia', models.FloatField()),
                ('fecha', models.DateField()),
                ('bodegaDestino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bodegaDestino', to='app_inventarioBodega.bodega')),
                ('bodegaOrigen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bodegaOrigen', to='app_inventarioBodega.bodega')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto', to='app_inventarioBodega.producto')),
            ],
        ),
    ]
