# Generated by Django 3.2.3 on 2021-07-26 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_inventarioBodega', '0003_remove_producto_apelllido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='proveedor',
        ),
    ]
