# Generated by Django 3.2.5 on 2021-07-24 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_inventarioBodega', '0003_transferencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordenVenta', models.CharField(max_length=5)),
                ('cantidadProducto', models.IntegerField()),
                ('PrecioProducto', models.IntegerField()),
                ('descuento', models.FloatField()),
                ('subTotal', models.FloatField()),
                ('totalVenta', models.FloatField()),
                ('fecha', models.DateField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='app_inventarioBodega.producto')),
            ],
        ),
    ]
