# Generated by Django 3.2.5 on 2021-07-29 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_inventarioBodega', '0003_alter_empleado_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='descuento',
        ),
    ]
