# Generated by Django 3.2.5 on 2021-07-26 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inventarioBodega', '0004_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='ISV',
            field=models.FloatField(default=0.15),
            preserve_default=False,
        ),
    ]
