# Generated by Django 3.2.3 on 2021-07-27 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_inventarioBodega', '0006_remove_producto_bodega'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='bodega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_inventarioBodega.bodega'),
        ),
        migrations.DeleteModel(
            name='Inventario',
        ),
    ]
