# Generated by Django 3.2.3 on 2021-07-27 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_inventarioBodega', '0007_auto_20210727_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='bodega',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_inventarioBodega.bodega'),
        ),
    ]
