# Generated by Django 3.2.3 on 2021-07-27 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_inventarioBodega', '0008_alter_producto_bodega'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='bodega',
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_inventarioBodega.bodega')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_inventarioBodega.producto')),
            ],
        ),
    ]
