# Generated by Django 3.2.3 on 2021-07-28 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_inventarioBodega', '0009_auto_20210727_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventarios_Bodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='producto',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='stock',
        ),
        migrations.AlterField(
            model_name='bodega',
            name='direccion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bodega',
            name='encargado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_inventarioBodega.empleado'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(blank=True, choices=[('1', 'Lácteos'), ('2', 'Carnes'), ('3', 'Bebidas'), ('4', 'Limpieza'), ('5', 'Abarrotes'), ('6', 'Enlatados'), ('7', 'Granos'), ('8', 'Dulces'), ('9', 'Otros')], default='1', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='unidades_medidas',
            field=models.CharField(blank=True, choices=[('1', 'Libras'), ('2', 'Kilos'), ('3', 'Cajas'), ('4', 'Docena'), ('5', 'Media docena'), ('6', 'Quintal'), ('7', 'Litros')], default='1', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='PrecioProducto',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='bodegaOrigen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bodegaOrigen', to='app_inventarioBodega.bodega'),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='cantidadProducto',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_inventarioBodega.producto'),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='totalTransferencia',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Inventario',
        ),
        migrations.AddField(
            model_name='inventarios_bodega',
            name='bodega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_inventarioBodega.bodega'),
        ),
        migrations.AddField(
            model_name='inventarios_bodega',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_inventarioBodega.producto'),
        ),
    ]
